services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nginx/nginx
    container_name: ${CONTAINER_NAME}
    image: imagen_nginx
    ports:
      - ${PORT_WEB}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netguitarranginx:
        ipv4_address: ${IP_WEB}
networks:
  netguitarranginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
