services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/node
    container_name: ${CONTAINER_NAME}
    image: imagen_node
    ports:
      - ${PORT_WEB}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netnode:
        ipv4_address: ${IP_WEB}
networks:
  netnode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
